export const types = {
  DEFAULT: 'DEFAULT',
  SET_CARD_DATA: 'SET_CARD_DATA',
  SET_COUNTRY_DATA: 'SET_COUNTRY_DATA',
  SET_CATEGORY_DATA: 'SET_CATEGORY_DATA',
  SET_COMPANY_DATA: 'SET_COMPANY_DATA',
  SET_USER_DATA: 'SET_USER_DATA',
  CHANGE_USER_DATA: 'CHANGE_USER_DATA'
};
